# Average annual rainfall in US!
# Function 1 for A3
#
# function to calculate average annual rainfall
# Load packages

library(devtools)
library(roxygen2)

avgrainfall <- function(df) {

  rainfall_total = sum(df[,1])
  avg_rainfall = (rainfall_total/length(df[,1]))

  # return function
  return(avg_rainfall)

}

# create sample df

library(tidyverse)

inches = runif(min = 1.1, max = 363, n = 50)
us = seq(1,50, by = 1)

total_rainfall_in = data.frame(inches, us)


# test function

avgrainfall(total_rainfall_in)


# R documentation
#' Mean Annual Rainfall
#' This function calculates average annual rainfall in the US.
#' data generated by Jonathan Hart & Derek Nguyen
#' @format df has 2 columns and 50 rows
#' \describe{
#' \item{rainfall_total}{total rainfall between 1.1 - 363 inches}
#' \item{us}{50 states in the US, so 1-50}}
#'
#' @authors Jonathan Hart and Derek Nguyen
#' @return avg annual rainfall in inches


